name: Backend Build

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Verify Python version
      run: |
        python --version
        pip --version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r apps/backend/requirements.txt
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: 1
        LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
        UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
        UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
        QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
        QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
        QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
        QSTASH_URL: ${{ secrets.QSTASH_URL }}
        API_URL: ${{ secrets.API_URL }}
        
    - name: Run setup.py
      run: |
        cd apps/backend
        # Start the server in the background
        python setup.py --run &
        SERVER_PID=$!
        
        # Wait for the server to start (timeout after 60 seconds)
        echo "Waiting for server to start..."
        for i in {1..60}; do
          if curl -s http://localhost:8000/health | grep -q '"status":"healthy"'; then
            echo "Server started successfully"
            # Kill the server process
            kill $SERVER_PID
            exit 0
          fi
          sleep 1
        done
        
        echo "Server failed to start within timeout"
        # Kill the server process if it's still running
        kill $SERVER_PID 2>/dev/null || true
        exit 1
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
        UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
        UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
        QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
        QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
        QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
        QSTASH_URL: ${{ secrets.QSTASH_URL }}
        API_URL: ${{ secrets.API_URL }}
        HOST: 0.0.0.0
        PORT: 8000
        DEBUG: "False"
      continue-on-error: false
      
    - name: Check for errors
      if: failure()
      run: |
        echo "::error::Backend build failed. Please check the logs for details."
        exit 1 