name: Backend Build

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'
  pull_request:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r apps/backend/requirements.txt
        
    - name: Run setup.py
      run: |
        cd apps/backend
        python setup.py --run
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 